name: ServerSpawn
version: '1.1-SNAPSHOT'
main: net.kaijane.serverSpawn.ServerSpawn
api-version: '1.21'

commands:
  serverspawn:
    description: Set the login location
    usage: /serverspawn set <world> <x> <y> <z>

# Default configuration
spawn:
  world: world
  x: 0
  y: 64
  z: 0